<?xml version="1.0" encoding="UTF-8"?>
<testng-results>
    <suite name="SampleSuite">
        <test name="SampleTest">
            <class name="com.example.tests.SampleTest">
                <test-method name="testCase1" status="PASS" duration-ms="120" started-at="2025-03-16T10:00:00Z" finished-at="2025-03-16T10:00:01Z"/>
                <test-method name="testCase2" status="FAIL" duration-ms="200" started-at="2025-03-16T10:00:02Z" finished-at="2025-03-16T10:00:02Z">
                    <exception class="java.lang.AssertionError">
                        <message><![CDATA[Expected value was X but got Y]]></message>
                        <stack-trace><![CDATA[com.example.tests.SampleTest.testCase2(SampleTest.java:25)]]></stack-trace>
                    </exception>
                </test-method>
                <test-method name="testCase3" status="PASS" duration-ms="150" started-at="2025-03-16T10:00:03Z" finished-at="2025-03-16T10:00:03Z"/>
                <test-method name="testCase4" status="FAIL" duration-ms="180" started-at="2025-03-16T10:00:04Z" finished-at="2025-03-16T10:00:04Z">
                    <exception class="java.lang.NullPointerException">
                        <message><![CDATA[Null reference encountered]]></message>
                        <stack-trace><![CDATA[com.example.tests.SampleTest.testCase4(SampleTest.java:40)]]></stack-trace>
                    </exception>
                </test-method>
                <test-method name="testCase5" status="PASS" duration-ms="170" started-at="2025-03-16T10:00:05Z" finished-at="2025-03-16T10:00:05Z"/>
                <test-method name="testCase6" status="FAIL" duration-ms="210" started-at="2025-03-16T10:00:06Z" finished-at="2025-03-16T10:00:06Z">
                    <exception class="java.lang.ArrayIndexOutOfBoundsException">
                        <message><![CDATA[Index out of bounds]]></message>
                        <stack-trace><![CDATA[com.example.tests.SampleTest.testCase6(SampleTest.java:55)]]></stack-trace>
                    </exception>
                </test-method>
                <test-method name="testCase7" status="PASS" duration-ms="160" started-at="2025-03-16T10:00:07Z" finished-at="2025-03-16T10:00:07Z"/>
                <test-method name="testCase8" status="FAIL" duration-ms="220" started-at="2025-03-16T10:00:08Z" finished-at="2025-03-16T10:00:08Z">
                    <exception class="java.lang.IllegalArgumentException">
                        <message><![CDATA[Invalid argument passed]]></message>
                        <stack-trace><![CDATA[com.example.tests.SampleTest.testCase8(SampleTest.java:70)]]></stack-trace>
                    </exception>
                </test-method>
            </class>
        </test>
    </suite>
</testng-results>

